export const DEFAULT_FORM = {
  general: {
    operationName: '',
    directorName: '',
    childFullName: '',
    childDOB: '',
    childLivesWith: '',
    childHomeAddress: '',
    dateOfAdmission: '',
    dateOfWithdrawal: '',
    parentGuardianName: '',
    parentGuardianAddress: '',
    parent1Phone: '',
    parent2Phone: '',
    guardianPhone: '',
    custodyDocumentsOnFile: '',
  },
  emergency: {
    contactName: '',
    contactRelationship: '',
    contactPhone: '',
    contactAddress: '',
  },
  authorizedPickup: [
    { name: '', phone: '' },
    { name: '', phone: '' },
    { name: '', phone: '' },
  ],
  consent: {
    transportation: { emergencyCare: false, fieldTrips: false, toFromHome: false, toFromSchool: false },
    fieldTripsConsent: '',
    fieldTripsComments: '',
    waterActivities: {
      waterTablePlay: false, sprinklerPlay: false, splashingWading: false,
      swimmingPools: false, aquaticPlaygrounds: false,
      canSwim: '', hasPhysicalRisk: '', wantsLifeJacket: '',
    },
    operationalPolicies: {
      disciplineGuidance: false, suspensionExpulsion: false, emergencyPlans: false,
      healthChecks: false, safeSleep: false, parentConcerns: false,
      physicalActivity: false, parentParticipation: false, releaseOfChildren: false,
      illnessExclusion: false, dispensingMedications: false, immunizationRequirements: false,
      mealsAndFood: false, visitWithoutApproval: false, inclusiveServices: false,
      contactCCR: false,
    },
    meals: {
      none: false, breakfast: false, morningSnack: false, lunch: false,
      afternoonSnack: false, supper: false, eveningSnack: false,
    },
    schedule: {
      monday: { am: '', pm: '' }, tuesday: { am: '', pm: '' },
      wednesday: { am: '', pm: '' }, thursday: { am: '', pm: '' },
      friday: { am: '', pm: '' }, saturday: { am: '', pm: '' },
      sunday: { am: '', pm: '' },
    },
    parentsRightsReceived: false,
  },
  specialCare: {
    environmentalAllergies: false, foodIntolerances: false, existingIllness: false,
    previousSeriousIllness: false, injuriesHospitalizations: false,
    activityLimitations: false, reasonableAccommodations: false,
    adaptiveEquipment: false, symptoms: false, longTermMedications: false,
    other: false, otherDescription: '',
    explanationOfNeeds: '',
    diagnosedFoodAllergies: '',
    foodAllergyEmergencyPlanDate: '',
  },
  school: {
    schoolName: '', schoolPhone: '',
    walkPermission: false, busPermission: false, siblingPermission: false,
    otherPickupLocations: '',
  },
  emergencyMedical: {
    physicianName: '', physicianAddress: '', physicianPhone: '',
    facilityName: '', facilityAddress: '', facilityPhone: '',
  },
  exclusion: {
    conscienceAffidavit: false, visionHearingAffidavit: false,
    visionRight: '', visionLeft: '', visionResult: '',
    hearingRight1000: '', hearingRight2000: '', hearingRight4000: '', hearingRightResult: '',
    hearingLeft1000: '', hearingLeft2000: '', hearingLeft4000: '', hearingLeftResult: '',
  },
  admission: {
    option: '',
    healthCareName: '', healthCareAddress: '',
  },
  vaccines: {
    hepatitisB: { d1: '', d2: '', d3: '' },
    rotavirus: { d1: '', d2: '', d3: '' },
    dtap: { d1: '', d2: '', d3: '', d4: '', d5: '' },
    hib: { d1: '', d2: '', d3: '', d4: '' },
    pneumococcal: { d1: '', d2: '', d3: '', d4: '' },
    ipv: { d1: '', d2: '', d3: '', d4: '' },
    influenza: { d1: '', d2: '' },
    mmr: { d1: '', d2: '' },
    varicella: { d1: '', d2: '' },
    hepatitisA: { d1: '', d2: '' },
    varicellaDisease: false,
    varicellaDate: '',
    tbResult: '', tbDate: '',
  },
};
